### ISSUE TITLE
broken link on https://laedit.net/2016/09/29/integrate-sonarqube-in-a-dotnet-project-with-appveyor.html

### ISSUE THREAD

**Issue by mattumotu** [laedit/laedit.net#1]
Page: 
https://laedit.net/2016/09/29/integrate-sonarqube-in-a-dotnet-project-with-appveyor.html

Section: 
/d:sonar.login: your login or authentication token. If login is used, you must use the sonar.password with your password as well but this is highly unsecure.

Broken link: https://laedit.net/2016/09/29/docs.sonarqube.org/display/SONAR/User+Token which is a 404

**Comment by laedit** [comment]
Thanks a lot, I will fix it asap :smile:
